export const TOGGLE_OBJECTIVE = 'TOGGLE_OBJECTIVE';
export const DELETE_TASK = 'DELETE_TASK';
export const RECEIVE_ALPHA_STATES = 'RECEIVE_ALPHA_STATES';
export const TOGGLE_CRITERIA = 'TOGGLE_CRITERIA';
export const CHECK_ALL_CRITERIA = 'CHECK_ALL_CRITERIA';
export const UNCHECK_ALL_CRITERIA = 'UNCHECK_ALL_CRITERIA';
export const RENAME_TASK = 'RENAME_TASK';